name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # バージョンをv3に更新

    - name: Setup Node.js
      uses: actions/setup-node@v3  # バージョンをv3に更新
      with:
        node-version: '16'  # Node.js 16を明示的に指定

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
